import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {resolve} from 'node:path';
import ts from 'typescript';
const out=resolve('.sites-runtime/regression');mkdirSync(out,{recursive:true});
for(const [input,name] of [['app/config.ts','config'],['app/server.ts','server'],['app/api/data/route.ts','route']]){let src=readFileSync(input,'utf8').replaceAll("'cloudflare:workers'","'./runtime.mjs'").replaceAll("'./config'","'./config.mjs'").replaceAll("'../../server'","'./server.mjs'");writeFileSync(`${out}/${name}.mjs`,ts.transpileModule(src,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText)}
writeFileSync(`${out}/runtime.mjs`, `import {DatabaseSync} from 'node:sqlite';export const sql=new DatabaseSync(':memory:');class Statement{constructor(s,args=[]){this.s=s;this.args=args}bind(...args){return new Statement(this.s,args)}exec(){const s=sql.prepare(this.s);if(/^\\s*(SELECT|.*RETURNING)/is.test(this.s)){const rows=s.all(...this.args);return {results:rows,meta:{changes:rows.length}}}const r=s.run(...this.args);return {results:[],meta:{changes:Number(r.changes)}}}async first(){return sql.prepare(this.s).get(...this.args)??null}async all(){return {results:sql.prepare(this.s).all(...this.args)}}async run(){return this.exec()}}export const env={DB:{prepare:s=>new Statement(s),async batch(stmts){sql.exec('BEGIN IMMEDIATE');try{const r=stmts.map(s=>s.exec());sql.exec('COMMIT');return r}catch(e){sql.exec('ROLLBACK');throw e}}},AUTH_MODE:'password',ADMIN_PASSWORD:'test-password-never-deployed'};`);
const {sql,env}=await import(`${out}/runtime.mjs`);sql.exec(readFileSync('drizzle/0000_lively_puma.sql','utf8'));
const S=await import(`${out}/server.mjs`),C=await import(`${out}/config.mjs`),API=await import(`${out}/route.mjs`);let passed=0;const results=[];
async function test(name,fn){try{await fn();passed++;results.push({name,passed:true});console.log('PASS',name)}catch(e){results.push({name,passed:false,error:e.message});console.error('FAIL',name,e);process.exitCode=1}}
let counter=1000;const day=C.addDays(C.today(),2);const base=()=>({date:day,time:'19:00',adults:2,children:0,name:'Cliente DEMO',phone:'+3900000'+(++counter),email:'demo@example.invalid',privacy:true,token:S.random(),idempotency:S.random()});
async function settings(patch){const c=await S.config();await S.saveSettings({settings:{...c.c,...patch},version:c.version})}
function reset(){sql.exec('DELETE FROM reservations;DELETE FROM outbox;DELETE FROM audit;DELETE FROM settings;DELETE FROM rate_limits;')}
await test('Initial automatic DEMO settings',async()=>assert.equal((await S.config()).c.mode,'automatic'));
let b=base(),r;
await test('Persistent insert and automatic confirmed status',async()=>{r=await S.create(b);assert.equal(r.status,'confirmed');assert.equal(sql.prepare('SELECT COUNT(*) n FROM reservations').get().n,1);assert.equal(r.adults,2);assert.match(r.code,/^DEMO-/)});
await test('Token hash only and public response privacy',async()=>{const row=sql.prepare('SELECT * FROM reservations').get();assert.notEqual(row.token_hash,b.token);assert.equal(row.token_hash,await S.hash(b.token));assert(!('token_hash' in r));assert(!('internal_notes' in r));assert(!('idempotency' in r))});
await test('Idempotent retry returns one record',async()=>assert.equal((await S.create(b)).id,r.id));
await test('Unpredictable token lookup / invalid token rejected',async()=>{assert.equal((await S.byToken(b.token)).id,r.id);await assert.rejects(S.byToken(S.random()),e=>e.status===404)});
await test('Request change preserves date and confirmed status',async()=>{r=await S.customerChange({action:'change',token:b.token,version:r.version,request:'Vorrei arrivare alle 20:00'});assert.equal(r.time,'19:00');assert.equal(r.status,'confirmed');assert(r.change_request)});
await test('Optimistic locking rejects stale customer update without side effects',async()=>{const events=sql.prepare('SELECT COUNT(*) n FROM outbox').get().n,audits=sql.prepare('SELECT COUNT(*) n FROM audit').get().n;await assert.rejects(S.customerChange({action:'cancel',token:b.token,version:1}),e=>e.status===409);assert.equal(sql.prepare('SELECT COUNT(*) n FROM outbox').get().n,events);assert.equal(sql.prepare('SELECT COUNT(*) n FROM audit').get().n,audits)});
await test('Cancellation releases capacity and updates ICS',async()=>{r=await S.customerChange({action:'cancel',token:b.token,version:r.version});assert.equal(r.status,'cancelled');assert.match(S.calendar(r),/STATUS:CANCELLED/)});
await test('Invalid booking rejected server side',async()=>{await assert.rejects(S.create({...base(),adults:0}));await assert.rejects(S.create({...base(),privacy:false}));await assert.rejects(S.create({...base(),date:'2026-02-30'}))});
await test('Honeypot and rate limiting',async()=>{await assert.rejects(S.create({...base(),website:'spam'}));for(let i=0;i<3;i++)await S.rate('test',3);await assert.rejects(S.rate('test',3),e=>e.status===429)});
await test('Automatic confirmation overrides legacy manual setting',async()=>{reset();await settings({mode:'manual',capacity:2});assert.equal((await S.config()).c.mode,'automatic');const x=await S.create(base());assert.equal(x.status,'confirmed');assert.match(S.calendar(x),/STATUS:CONFIRMED/);assert(!await S.availability(day,2,0).then(x=>x.includes('19:30')))});
await test('Simultaneous requests cannot overbook or emit ghost events',async()=>{reset();await settings({capacity:2,mode:'automatic'});const all=await Promise.allSettled(Array.from({length:6},()=>S.create(base())));assert.equal(all.filter(x=>x.status==='fulfilled').length,1);assert.equal(sql.prepare('SELECT SUM(adults+children) n FROM reservations').get().n,2);assert.equal(sql.prepare('SELECT COUNT(*) n FROM audit').get().n,1);assert.equal(sql.prepare('SELECT COUNT(*) n FROM outbox').get().n,4)});
await test('Overlapping slots blocked but end boundary allowed',async()=>{assert(!(await S.availability(day,2,0)).includes('20:30'));assert((await S.availability(day,2,0)).includes('21:00'))});
await test('Italian phone normalization prevents overlapping duplicate',async()=>{reset();const p=base();p.phone='333 000 0000';await S.create(p);await assert.rejects(S.create({...base(),phone:'+39 3330000000',time:'19:30'}),e=>e.status===409)});
await test('Children included or excluded by configuration',async()=>{reset();await settings({capacity:2,countChildren:true});await assert.rejects(S.create({...base(),children:1}),e=>e.status===409);await settings({countChildren:false});const x=await S.create({...base(),children:1});assert.equal(x.children,1)});
await test('Groups confirm automatically and respect capacity',async()=>{reset();await settings({mode:'automatic',capacity:20});const g=await S.create({...base(),adults:12,source:'group'});assert.equal(g.status,'confirmed');assert(!(await S.availability(day,12,0,true)).includes('19:30'));await assert.rejects(S.create({...base(),time:'19:30',adults:12,source:'group'}),e=>e.status===409)});
await test('Admin edit cannot exceed capacity',async()=>{reset();await settings({capacity:4});const a=await S.create(base()),b=await S.create({...base(),time:'21:00'});await assert.rejects(S.update({id:b.id,version:b.version,date:day,time:'19:00',adults:3,status:'confirmed'},'admin'),e=>e.status===409);await S.update({id:a.id,version:a.version,status:'arrived',internal_notes:'Riservata'},'admin');assert.equal(sql.prepare('SELECT status FROM reservations WHERE id=?').get(a.id).status,'arrived')});
await test('Closures and exceptional availability override weekly schedule',async()=>{reset();await settings({closures:[day]});assert.deepEqual(await S.availability(day,2,0),[]);await settings({closures:[],special:{[day]:{times:['18:00'],capacity:3}}});assert.deepEqual(await S.availability(day,2,0),['18:00'])});
await test('Unauthorized admin and spoofed identity denied',async()=>{assert.equal((await API.GET(new Request('http://localhost/api/data?action=admin'))).status,403);await assert.rejects(S.admin(new Request('https://external.example/api',{headers:{'oai-authenticated-user-id':'owner','Authorization':'Bearer wrong-password'}})),e=>e.status===403)});
await test('Password is the only admin access method',async()=>{assert.equal(await S.admin(new Request('https://site.example/api',{headers:{Authorization:'Bearer '+env.ADMIN_PASSWORD}})),'restaurant-admin');await assert.rejects(S.admin(new Request('https://site.example/api',{headers:{'oai-authenticated-user-id':'owner'}})),e=>e.status===403);env.AUTH_MODE='sites';await assert.rejects(S.admin(new Request('https://site.example/api',{headers:{Authorization:'Bearer '+env.ADMIN_PASSWORD}})),e=>e.status===503);env.AUTH_MODE='password'});
await test('Cross-origin writes and malformed JSON rejected',async()=>{assert.equal((await API.POST(new Request('http://localhost/api/data',{method:'POST',headers:{origin:'https://attacker.example','Content-Type':'application/json'},body:'{}'}))).status,403);assert.equal((await API.POST(new Request('http://localhost/api/data',{method:'POST',headers:{'Content-Type':'application/json'},body:'x'}))).status,400)});
await test('Settings stale versions rejected',async()=>{const c=await S.config();await S.saveSettings({settings:c.c,version:c.version});await assert.rejects(S.saveSettings({settings:c.c,version:c.version}),e=>e.status===409)});
await test('Timezone conversion summer/winter and exact last day',async()=>{assert.equal(C.romeTimestamp('2026-09-12','19:00'),Date.parse('2026-09-12T17:00:00Z')/1000);assert.equal(C.romeTimestamp('2026-12-12','19:00'),Date.parse('2026-12-12T18:00:00Z')/1000)});
await test('No simulated email: all outbox events not configured',async()=>assert.equal(sql.prepare("SELECT COUNT(*) n FROM outbox WHERE status <> 'not_configured'").get().n,0));
await test('DEMO seed is safe and idempotent',async()=>{reset();assert.equal((await S.seedDemo('local-admin')).created,3);assert.equal((await S.seedDemo('local-admin')).created,0);assert.equal(sql.prepare('SELECT COUNT(*) n FROM reservations').get().n,3);assert.equal(sql.prepare("SELECT COUNT(*) n FROM reservations WHERE source='phone' AND name LIKE '%DEMO'").get().n,3)});
await test('Retention purge removes expired demo and notification records',async()=>{reset();await S.config();const x=await S.create(base());sql.prepare('UPDATE reservations SET end=? WHERE id=?').run(1,x.id);const p=await S.purge();assert.equal(p.removed,1);assert.equal(sql.prepare('SELECT COUNT(*) n FROM outbox').get().n,0)});
console.log(`${passed}/${results.length} passed`);writeFileSync('docs/REGRESSION-RESULTS.json',JSON.stringify({date:new Date().toISOString(),engine:'Node SQLite executing unmodified application SQL; mocked D1 interface, not hosted D1',passed,total:results.length,results},null,2)+'\n');
