export const VENUE={name:'La Lanterna Verde',address:'Via Napoli 99, 70123 Bari',phone:'+39 346 306 7204',email:'lalanternaverde.bari@gmail.com',instagram:'https://www.instagram.com/la.lanternaverde/',menu:'https://www.leggimenu.it/menu/79qk5fan79p1/',delivery:'https://www.justeat.it/restaurants-la-lanterna-verde-bari/menu',maps:'https://www.google.com/maps/search/?api=1&query=La+Lanterna+Verde+Via+Napoli+99+Bari'};
export type Settings={mode:'manual'|'automatic';capacity:number;slotMinutes:number;stayMinutes:number;minNoticeMinutes:number;maxDays:number;maxPeople:number;maxGroupPeople:number;countChildren:boolean;retentionDays:number;weekly:Record<string,string[]>;closures:string[];special:Record<string,{times:string[];capacity:number}>;message:string;groupMessage:string};
export const DEFAULT_SETTINGS:Settings={mode:'manual',capacity:30,slotMinutes:30,stayMinutes:120,minNoticeMinutes:60,maxDays:60,maxPeople:10,maxGroupPeople:50,countChildren:true,retentionDays:90,weekly:{'0':['19:00','23:00'],'1':['19:00','23:00'],'2':[],'3':['19:00','23:00'],'4':['19:00','23:00'],'5':['19:00','23:00'],'6':['19:00','23:00']},closures:[],special:{},message:'Richiesta ricevuta – in attesa di conferma del ristorante',groupMessage:'Per gruppi oltre 10 ospiti invia una richiesta. Il tavolo sarà riservato solo dopo la conferma del ristorante.'};
export const STATUS:Record<string,string>={pending:'In attesa',confirmed:'Confermata',rejected:'Rifiutata',cancelled:'Annullata dal cliente',arrived:'Arrivata',completed:'Completata',absent:'Assente'};
export function today(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Rome',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
export function addDays(date:string,n:number){return new Date(Date.parse(date+'T12:00:00Z')+n*86400000).toISOString().slice(0,10)}
export function formatDate(date:string){return new Intl.DateTimeFormat('it-IT',{dateStyle:'full',timeZone:'Europe/Rome'}).format(new Date(date+'T12:00:00Z'))}
export function romeTimestamp(date:string,time:string){let t=Date.parse(date+'T'+time+':00Z');for(let i=0;i<3;i++){const parts=new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Rome',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).format(new Date(t));const local=Date.parse(parts.replace(' ','T')+'Z');t+=Date.parse(date+'T'+time+':00Z')-local;}return Math.floor(t/1000)}
export function schedule(date:string,c:Settings,now=Date.now()/1000){if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!Number.isFinite(Date.parse(date+'T12:00:00Z'))||new Date(date+'T12:00:00Z').toISOString().slice(0,10)!==date||date<today()||date>addDays(today(),c.maxDays)||c.closures.includes(date))return [];const day=new Date(date+'T12:00:00Z').getUTCDay();let times=c.special[date]?.times;if(!times){const hours=c.weekly[String(day)]??[];times=[];if(hours.length===2){const min=(x:string)=>Number(x.slice(0,2))*60+Number(x.slice(3));for(let m=min(hours[0]);m<min(hours[1]);m+=c.slotMinutes)times.push(String(Math.floor(m/60)).padStart(2,'0')+':'+String(m%60).padStart(2,'0'));}}return times.map(time=>({time,start:romeTimestamp(date,time),end:romeTimestamp(date,time)+c.stayMinutes*60,capacity:c.special[date]?.capacity??c.capacity})).filter(s=>s.start>=now+c.minNoticeMinutes*60)}
