import {env} from 'cloudflare:workers';
import {z} from 'zod';
import {DEFAULT_SETTINGS,Settings,schedule,STATUS,today,addDays} from './config';
export const tenant='demo';
export const db=()=>{if(!env.DB)throw new AppError("Database non configurato",503);return env.DB};
export class AppError extends Error {constructor(message:string,public status=400){super(message)}}
export const random=()=>Array.from(crypto.getRandomValues(new Uint8Array(32)),n=>n.toString(16).padStart(2,'0')).join('');
export async function hash(s:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s))),n=>n.toString(16).padStart(2,'0')).join('')}
export async function config(){await db().prepare('INSERT OR IGNORE INTO settings (tenant,value) VALUES (?,?)').bind(tenant,JSON.stringify(DEFAULT_SETTINGS)).run();const row=await db().prepare('SELECT value,version FROM settings WHERE tenant=?').bind(tenant).first<{value:string;version:number}>();return {c:JSON.parse(row!.value) as Settings,raw:row!.value,version:row!.version}}
const time=z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/);
const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>Number.isFinite(Date.parse(v+'T12:00Z'))&&new Date(v+'T12:00Z').toISOString().slice(0,10)===v,'Data non valida');
const txt=z.string().trim();
export const bookingSchema=z.object({date,time,adults:z.number().int().min(1).max(100),children:z.number().int().min(0).max(99),name:txt.min(3,'Inserisci nome e cognome').max(100),phone:txt.regex(/^\+?[\d\s().-]+$/,'Numero non valido').refine(v=>v.replace(/\D/g,'').length>=7&&v.replace(/\D/g,'').length<=15,'Numero non valido'),email:txt.email('Email non valida').max(254),allergies:txt.max(500).default(''),highchair:z.boolean().default(false),occasion:txt.max(120).default(''),notes:txt.max(1000).default(''),privacy:z.literal(true),marketing:z.boolean().default(false),source:z.enum(['website','group','phone']).default('website'),token:z.string().regex(/^[a-f0-9]{64}$/),idempotency:z.string().regex(/^[a-f0-9]{64}$/),website:z.string().max(0).default('')});
export const settingsSchema=z.object({mode:z.enum(['manual','automatic']),capacity:z.number().int().min(1).max(500),slotMinutes:z.number().int().min(5).max(120),stayMinutes:z.number().int().min(15).max(360),minNoticeMinutes:z.number().int().min(0).max(10080),maxDays:z.number().int().min(1).max(365),maxPeople:z.number().int().min(1).max(100),maxGroupPeople:z.number().int().min(11).max(100),countChildren:z.boolean(),retentionDays:z.number().int().min(1).max(365),weekly:z.record(z.string().regex(/^[0-6]$/),z.array(time).refine(a=>a.length===0||a.length===2&&a[0]<a[1],'Orario di apertura prima della chiusura')),closures:z.array(date).max(366),special:z.record(date,z.object({times:z.array(time).max(100),capacity:z.number().int().min(1).max(500)})),message:txt.min(5).max(500),groupMessage:txt.min(5).max(500)});
const active="(status IN ('confirmed','arrived') OR (status='pending' AND source<>'group'))";
function guard(start:number,end:number,count:number,capacity:number,c:Settings,except='') {const size=c.countChildren?'adults+children':'adults';return {sql:`(SELECT COALESCE(MAX((SELECT COALESCE(SUM(${size}),0) FROM reservations r WHERE r.tenant=? AND ${active} AND r.id<>? AND r.start<=p.t AND r.end>p.t)),0) FROM (SELECT ? AS t UNION SELECT start AS t FROM reservations WHERE tenant=? AND ${active} AND id<>? AND start>? AND start<?) p)+?<=?`,args:[tenant,except,start,tenant,except,start,end,count,capacity]}}
export async function availability(day:string,adults:number,children:number,group=false){date.parse(day);if(!Number.isInteger(adults)||adults<1||!Number.isInteger(children)||children<0||adults+children>100)throw new AppError('Numero di persone non valido');const {c}=await config();if(adults+children>(group?c.maxGroupPeople:c.maxPeople))throw new AppError('Numero di persone oltre il limite');const slots=schedule(day,c);if(group)return slots.map(x=>x.time);const rows=(await db().prepare(`SELECT start,end,adults,children FROM reservations WHERE tenant=? AND ${active} AND end>? AND start<?`).bind(tenant,slots[0]?.start??0,slots.at(-1)?.end??0).all<any>()).results;return slots.filter(s=>[s.start,...rows.filter(r=>r.start>s.start&&r.start<s.end).map(r=>r.start)].every(t=>rows.filter(r=>r.start<=t&&r.end>t).reduce((n,r)=>n+r.adults+(c.countChildren?r.children:0),0)+adults+(c.countChildren?children:0)<=s.capacity)).map(s=>s.time)}
export async function rate(key:string,max=12){const window=Math.floor(Date.now()/600000),k=await hash(key+':'+window);const r=await db().prepare('INSERT INTO rate_limits (key,count,expires) VALUES (?,1,?) ON CONFLICT(key) DO UPDATE SET count=count+1 RETURNING count').bind(k,(window+1)*600).first<{count:number}>();if(r!.count>max)throw new AppError('Troppe richieste. Riprova fra qualche minuto.',429)}
export async function admin(req:Request){const values=env as unknown as Record<string,string>;const ids=(values.ADMIN_USER_IDS??'').split(',').map(s=>s.trim()).filter(Boolean);const uid=req.headers.get('oai-authenticated-user-id');if(values.AUTH_MODE==='sites'&&uid&&ids.includes(uid))return uid;const hostname=new URL(req.url).hostname;const local=['localhost','127.0.0.1'].includes(hostname);if(local&&values.ALLOW_LOCAL_ADMIN==='true'&&values.LOCAL_ADMIN_TOKEN&&req.headers.get('authorization')===`Bearer ${values.LOCAL_ADMIN_TOKEN}`)return 'local-admin';throw new AppError('Accesso riservato agli amministratori autorizzati.',403)}
export function safe(r:any){const {token_hash,idempotency,internal_notes,tenant:_,...rest}=r;return rest}
function event(id:string,kind:string,version:number,op:string){return db().prepare('INSERT OR IGNORE INTO outbox (id,reservation_id,tenant,kind,status,created_at) SELECT ?,id,tenant,?,\'not_configured\',? FROM reservations WHERE id=? AND version=? AND EXISTS(SELECT 1 FROM audit WHERE id=?)').bind(id+':'+version+':'+kind,kind,Math.floor(Date.now()/1000),id,version,op)}
function log(id:string,action:string,actor:string,version:number,op:string){return db().prepare('INSERT OR IGNORE INTO audit (id,reservation_id,actor,action,created_at) SELECT ?,id,?,?,? FROM reservations WHERE id=? AND version=? AND changes()=1').bind(op,actor,action,Math.floor(Date.now()/1000),id,version)}
export async function create(input:unknown,actor='customer') {const b=bookingSchema.parse(input);if(actor==='customer'&&b.source==='phone')throw new AppError('Fonte non consentita');const {c,raw}=await config();const count=b.adults+b.children;if(count>(b.source==='group'?c.maxGroupPeople:b.source==='phone'?100:c.maxPeople))throw new AppError('Usa la richiesta per gruppi numerosi');const slot=schedule(b.date,c).find(s=>s.time===b.time);if(!slot)throw new AppError('Questo orario non è più disponibile.',409);const tokenHash=await hash(b.token),prior=await db().prepare('SELECT * FROM reservations WHERE tenant=? AND idempotency=?').bind(tenant,b.idempotency).first<any>();if(prior){if(prior.token_hash!==tokenHash)throw new AppError('Richiesta duplicata',409);return safe(prior)}const op=crypto.randomUUID();const id=crypto.randomUUID(),code='DEMO-'+random().slice(0,16).toUpperCase(),now=Math.floor(Date.now()/1000),phone=b.phone.replace(/[\s().-]/g,'').replace(/^0039/,'+39').replace(/^(3\d{9})$/,'+39$1');const status=b.source==='group'||c.mode==='manual'?'pending':'confirmed';const g=guard(slot.start,slot.end,b.adults+(c.countChildren?b.children:0),slot.capacity,c);const insert=db().prepare(`INSERT INTO reservations (id,tenant,code,token_hash,idempotency,date,time,start,end,adults,children,name,phone,email,allergies,highchair,occasion,notes,status,source,privacy,marketing,created_at,updated_at) SELECT ${Array(24).fill('?').join(',')} WHERE (?=1 OR ${g.sql}) AND NOT EXISTS(SELECT 1 FROM reservations WHERE tenant=? AND phone=? AND start<? AND end>? AND status IN ('pending','confirmed','arrived')) AND (SELECT value FROM settings WHERE tenant=?)=?`).bind(id,tenant,code,tokenHash,b.idempotency,b.date,b.time,slot.start,slot.end,b.adults,b.children,b.name,phone,b.email,b.allergies,Number(b.highchair),b.occasion,b.notes,status,b.source,1,Number(b.marketing),now,now,Number(b.source==='group'),...g.args,tenant,phone,slot.end,slot.start,tenant,raw);let result;try{result=await db().batch([insert,log(id,'created',actor,1,op),event(id,'received',1,op),event(id,'restaurant_new',1,op),...(status==='confirmed'?[event(id,'confirmed',1,op),event(id,'reminder',1,op)]:[])])}catch(e){const prior=await db().prepare('SELECT * FROM reservations WHERE tenant=? AND idempotency=? AND token_hash=?').bind(tenant,b.idempotency,tokenHash).first<any>();if(prior)return safe(prior);throw e}if(!result[0].meta.changes)throw new AppError('Disponibilità cambiata o richiesta già presente per questo telefono. Scegli un altro orario.',409);return safe(await db().prepare('SELECT * FROM reservations WHERE id=?').bind(id).first())}
export async function byToken(token:string){if(!/^[a-f0-9]{64}$/.test(token))throw new AppError('Collegamento non valido',404);const r=await db().prepare('SELECT * FROM reservations WHERE tenant=? AND token_hash=?').bind(tenant,await hash(token)).first<any>();if(!r)throw new AppError('Prenotazione non trovata o scaduta',404);return r}
export async function customerChange(input:any){const r=await byToken(String(input.token??''));if(!['pending','confirmed'].includes(r.status))throw new AppError('La richiesta non è più modificabile',409);const version=z.number().int().parse(input.version);const cancel=input.action==='cancel';const value=cancel?'cancelled':txt.min(5).max(500).parse(input.request);const op=crypto.randomUUID();const statement=cancel?'status=?':'change_request=?';const res=await db().batch([db().prepare(`UPDATE reservations SET ${statement},version=version+1,updated_at=? WHERE id=? AND version=? AND status IN ('pending','confirmed')`).bind(value,Math.floor(Date.now()/1000),r.id,version),log(r.id,cancel?'cancelled':'change_requested','customer',version+1,op),event(r.id,cancel?'cancelled':'change_requested',version+1,op)]);if(!res[0].meta.changes)throw new AppError('La prenotazione è cambiata. Aggiorna la pagina.',409);return safe(await byToken(input.token))}
export async function update(input:any,actor:string){const r=await db().prepare('SELECT * FROM reservations WHERE tenant=? AND id=?').bind(tenant,txt.parse(input.id)).first<any>();if(!r)throw new AppError('Prenotazione non trovata',404);const status=z.enum(['pending','confirmed','rejected','cancelled','arrived','completed','absent']).parse(input.status??r.status),day=date.parse(input.date??r.date),tm=time.parse(input.time??r.time),adults=z.number().int().min(1).max(100).parse(input.adults??r.adults),children=z.number().int().min(0).max(99).parse(input.children??r.children);if(adults+children>100)throw new AppError('Massimo 100 persone');const version=z.number().int().parse(input.version),{c,raw}=await config();const isActive=['confirmed','arrived'].includes(status)||status==='pending'&&r.source!=='group';const changed=day!==r.date||tm!==r.time||adults!==r.adults||children!==r.children;const needsSlot=isActive&&(changed||!['pending','confirmed','arrived'].includes(r.status)||r.source==='group'&&r.status==='pending');const slot=schedule(day,c).find(s=>s.time===tm);if(needsSlot&&!slot)throw new AppError('Data o fascia non disponibile',409);const start=changed?slot?.start:r.start,end=changed?slot?.end:r.end;if(!start||!end)throw new AppError('Data o fascia non valida');const g=guard(start,end,adults+(c.countChildren?children:0),slot?.capacity??c.capacity,c,r.id);const stmt=db().prepare(`UPDATE reservations SET date=?,time=?,start=?,end=?,adults=?,children=?,status=?,notes=?,internal_notes=?,change_request=?,version=version+1,updated_at=? WHERE id=? AND tenant=? AND version=? AND (?=0 OR ${g.sql}) AND (?=0 OR NOT EXISTS(SELECT 1 FROM reservations WHERE tenant=? AND id<>? AND phone=? AND start<? AND end>? AND status IN ('pending','confirmed','arrived'))) AND (SELECT value FROM settings WHERE tenant=?)=?`).bind(day,tm,start,end,adults,children,status,txt.max(1000).parse(input.notes??r.notes),txt.max(2000).parse(input.internal_notes??r.internal_notes),input.resolveChange?'':r.change_request,Math.floor(Date.now()/1000),r.id,tenant,version,Number(isActive),...g.args,Number(isActive),tenant,r.id,r.phone,end,start,tenant,raw);const op=crypto.randomUUID();const result=await db().batch([stmt,log(r.id,'updated:'+status,actor,version+1,op),event(r.id,status,version+1,op),...(status==='confirmed'?[event(r.id,'reminder',version+1,op)]:[])]);if(!result[0].meta.changes)throw new AppError('Capienza insufficiente, telefono già prenotato o dati aggiornati da un altro operatore. Ricarica.',409);return {ok:true}}
export async function saveSettings(input:any){const c=settingsSchema.parse(input.settings),version=z.number().int().parse(input.version);const result=await db().prepare('UPDATE settings SET value=?,version=version+1 WHERE tenant=? AND version=?').bind(JSON.stringify(c),tenant,version).run();if(!result.meta.changes)throw new AppError('Impostazioni cambiate. Ricarica prima di salvare.',409);return {ok:true}}
export async function purge(){const {c}=await config();const cutoff=Math.floor(Date.now()/1000)-c.retentionDays*86400;const result=await db().batch([db().prepare('DELETE FROM outbox WHERE reservation_id IN (SELECT id FROM reservations WHERE tenant=? AND end<?)').bind(tenant,cutoff),db().prepare('DELETE FROM audit WHERE reservation_id IN (SELECT id FROM reservations WHERE tenant=? AND end<?)').bind(tenant,cutoff),db().prepare('DELETE FROM reservations WHERE tenant=? AND end<?').bind(tenant,cutoff),db().prepare('DELETE FROM rate_limits WHERE expires<?').bind(Math.floor(Date.now()/1000))]);return {removed:result[2].meta.changes}}
export function calendar(r:any){const utc=(n:number)=>new Date(n*1000).toISOString().replace(/[-:]/g,'').replace('.000','');const state=['cancelled','rejected'].includes(r.status)?'CANCELLED':['confirmed','arrived','completed'].includes(r.status)?'CONFIRMED':'TENTATIVE';return ['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//La Lanterna Verde//Prenotazioni//IT','CALSCALE:GREGORIAN','BEGIN:VEVENT',`UID:${r.id}@lanterna-verde`,`SEQUENCE:${r.version}`,`DTSTAMP:${utc(r.updated_at)}`,`DTSTART:${utc(r.start)}`,`DTEND:${utc(r.end)}`,`STATUS:${state}`,`SUMMARY:DEMO La Lanterna Verde - ${STATUS[r.status]}`,'LOCATION:Via Napoli 99\\, Bari',`DESCRIPTION:${r.adults} adulti - ${r.children} bambini 0-4 anni. Codice ${r.code}`,'END:VEVENT','END:VCALENDAR',''].join('\r\n')}

export async function seedDemo(actor:string){const {c}=await config();let day=today();for(let i=0;i<c.maxDays&&!schedule(day,c).length;i++)day=addDays(day,1);const slots=schedule(day,c);if(!slots.length)throw new AppError('Nessuna data disponibile per gli esempi');let created=0;for(let i=0;i<3;i++){const key=await hash('seed-demo-v1-'+i);if(await db().prepare('SELECT id FROM reservations WHERE tenant=? AND idempotency=?').bind(tenant,key).first())continue;await create({date:day,time:slots[Math.min(i*2,slots.length-1)].time,adults:2,children:i===1?1:0,name:['Coppia DEMO','Famiglia DEMO','Amici DEMO'][i],phone:'+39000008000'+i,email:'demo'+i+'@example.invalid',privacy:true,notes:'Esempio fittizio DEMO',token:random(),idempotency:key,source:'phone'},actor);created++}return {created}}
